server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          #GitHub上面的git仓库名字
          uri: https://github.com/TurboS2021/springcloud-config.git
#          uri: git@github.com:TurboS2021/springcloud-config.git
          ####搜索目录
          search-paths:
            - springcloud-config
          username: TurboS2021
          password: Ly112240868.
      ####读取分支
      label: main

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
